### ISSUE TITLE
Menambahkan Service Worker

### ISSUE THREAD

**Issue by jefrydco** [dafiulh/cari-teks#1]
Hi Mas Dafiul, terima kasih telah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Daiful.

Mas juga menambahkan gaya CSS sendiri untuk aplikasi pencari teks pada video YouTube ini. Luar biasa Mas!

Namun saya ada 1 saran untuk kode yg Mas kirimkan yakni menambahkan Service Worker.

Saya lihat Mas sudah menambahkan berkas `manifest.json`. Berkas tersebut pada umumnya digunakan untuk Aplikasi Web Progresif/Progressive Web App/PWA. Namun sepertinya Mas belum menambahkan Service Worker sehingga fitur aplikasi web progresifnya belum bisa digunakan.

Dengan menambahkan Service Worker, aplikasi pencari teks pada video YouTube ini akan tetap bisa diakses secara luring/offline karena berkas-berkasnya di cache oleh peramban.

Saya juga lihat pada berkas `js/main.js` pada baris ke 6 Mas juga sudah menggunakan localStorage untuk menyimpan data ukuran secara lokal di peramban. 

https://github.com/dafiulh/cari-teks/blob/f8e10f70a06e3f4652bba426b335c0d2bacb5a8d/js/main.js#L6

Menggabungkan keduanya akan membantu aplikasi Mas agar dapat diakses secara luring/offline. Lebih lengkap mengenai Service Worker dan cara menambahkannya Mas dapat membaca pada tautan berikut, [Google Web Fundamentals - Service Workers](https://developers.google.com/web/fundamentals/primers/service-workers).

Semangat Mas! 😄

**Comment by daflh** [comment]
Awalnya memang mau saya kasih service worker mas, sehingga saya buat `manifest.json`-nya dulu. Tapi saya pikir-pikir lagi kok sepertinya sia-sia ya mas dikasih service worker, karena ini pake fetch API jadi tetap butuh koneksi internet walaupun udah di cache semua assetnya :sweat_smile:.
Kalau menurut mas-nya gimana?? Btw, makasih sarannya mas :smile:

**Comment by jefrydco** [comment]
Hi Mas iya Mas memang untuk mengakses API kita membutuhkan koneksi juga. Namun kita bisa juga melakukan cache untuk respons dari API tersebut Mas. Lebih lanjut mengenai caranya Mas dapat membaca pada tautan berikut, [PWA Workshop - Cache Strategy from REST API](https://pwa-workshop.js.org/4-api-cache/#cache-update-refresh).

Atau kalau misal Mas ngga mau ribet, Mas bisa menggunakan Workbox, lebih lanjut mengenai Workbox Mas bisa membaca pada tautan berikut, [Workbox - Get Started Guide](https://developers.google.com/web/tools/workbox/guides/get-started). Dengan menggunakan Workbox, banyak hal ribet ketika pendaftaran Service Worker disederhanakan cara penggunaannya Mas, jadi Mas bisa fokus untuk membangun aplikasinya saja.

Untuk melakukan cache pada REST API menggunakan Workbox juga yang perlu kita lakukan hanyalah menambahkan URL REST API nya dan Workbox akan melakukan sisanya untuk kita.

Namun kalau boleh saya sarankan, untuk belajar mungkin bisa menggunakan cara manual tanpa menggunakan Workbox terlebih dahulu Mas. Agar kita juga bisa memahami lebih dalam cara kerja Service Worker.

Mas juga bisa menambahkan mekanisme pengecekan ketersediaan koneksi internet menggunakan `navigator.onLine` API. Lebih lanjut mengenai API tersebut Mas dapat membaca pada tautan berikut, [Mozilla Developer Network - Navigator Online](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine).

Semangat selalu Mas! 😄

**Comment by daflh** [comment]
Baik mas, barusan sudah saya tambahkan service worker
2e78c06

Terima kasih mas atas masukannya :smile:
